### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by colomboipl** [influxdata/TICK-docker#3]
It failed on building from the dockerfile

**Comment by jonathanstiansen** [comment]
I had the same issue, I had better luck taking their independant dockerfiles - they seem to be the focus now. Not sure why.

**Comment by nathanielc** [comment]
@colomboipl @jonathanstiansen See #2 we are moving to a docker compose file instead of running all the processes in the same container. #2 is waiting on the official images being available.

**Comment by jonathanstiansen** [comment]
@nathanielc Thanks! Sounds great.
