### ISSUE TITLE
Telegraf, issue with Docker-Plugin

### ISSUE THREAD

**Issue by ArnoBuschmann** [influxdata/TICK-docker#7]
When adding the Docker plugin to the telegraf.config:
```
[[inputs.docker]]
endpoint = "unix:///var/run/docker.sock"
```
I get the error message
```
telegraf_1       | 2016/07/14 12:31:20 ERROR in input [docker]: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
Now for Telegraf itself this has been discussed already here: https://github.com/influxdata/telegraf/issues/1074
But the solution
```
sudo usermod -aG docker telegraf
```
seems not working when running telegraf itself in this TICK stack as a Docker container.

Also it makes no difference if I start TICK-docker with
```
docker-compose up
```
or
```
sudo docker-compose up
```
Any ideas how I can fix this?

**Comment by rossmcdonald** [comment]
Are you also mounting the unix socket in the Telegraf container? You can add it to the `docker-compose.yml` file like so (under the `telegraf` service):

```
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by ArnoBuschmann** [comment]
Awesome, that works nicely. Thanks Ross!

**Comment by xkfen** [comment]
same question.
but i have volumed the 

> Are you also mounting the unix socket in the Telegraf container? You can add it to the `docker-compose.yml` file like so (under the `telegraf` service):
> 
> ```
>     volumes:
>       - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
>       - /var/run/docker.sock:/var/run/docker.sock
> ```

hi , i have volumed the docker.sock, but i still got this err.
this err is occasionally appeared.
this is my telegraf-ds.yaml
`        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: telegraf-config
          mountPath: /etc/telegraf
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists  
      volumes:
      - name: sysro
        hostPath:
          path: /sys
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
`
